language: python
arch: amd64
os: linux
dist: bionic

git:
  depth: 3
  quiet: true
  autocrlf: input

python:
  - "2.7"
  - "3.6"

cache:
  directories:
    - $HOME/.cache/kodi_mock/addons

before_cache:
  - rm -rf $HOME/.cache/kodi_mock/addons/packages

install:
  - pip install coveralls
  - pip install pytest-cov
  - pip install https://github.com/willforde/kodi-addondev/archive/master.zip
  - pip install https://github.com/willforde/kodi-mock/archive/master.zip

script: pytest --cov
after_success: coveralls
